/**
 * @file	alDefineSampler.glsl
 * @author	Yosuke Mori  (C)Nintendo
 *
 * @brief	サンプラー定義
 */

#if defined( AGL_TARGET_GX2 )
#extension GL_EXT_Cafe : enable
#endif

#if defined( AGL_TARGET_GX2 )
	#define DEFINE_BINDING(gx2, nvn)	layout(binding = gx2)
#elif defined( AGL_TARGET_NVN )
	#define DEFINE_BINDING(gx2, nvn)	layout(binding = nvn)
#else
	#define DEFINE_BINDING(gx2, nvn)
#endif

/**
 *	バインディング場所定義
 */

// MIRROR は PROG_TEXTURE の仕組みでやりたい
// プロシージャルテクスチャを差し込むのはレンダーインフォ経由で指定して差し込みたい

#define BINDING_SAMPLER_BASE_COLOR					DEFINE_BINDING( 0, 0)
#define BINDING_SAMPLER_NORMAL						DEFINE_BINDING( 1, 1)
#define BINDING_SAMPLER_UNIFORM0					DEFINE_BINDING( 2, 2)
#define BINDING_SAMPLER_UNIFORM1					DEFINE_BINDING( 3, 3)
#define BINDING_SAMPLER_UNIFORM2					DEFINE_BINDING( 4, 4)
#define BINDING_SAMPLER_UNIFORM3					DEFINE_BINDING( 5, 5)
#define BINDING_SAMPLER_ENV_CUBE_MAP_ROUGHNESS		DEFINE_BINDING( 6, 6)
#define BINDING_SAMPLER_DEPTH						DEFINE_BINDING( 7, 7)
#define BINDING_SAMPLER_CUBEMAP_STRUCTURAL_COLOR	DEFINE_BINDING( 8, 8)
#define BINDING_SAMPLER_MATERIAL_LIGHT_CUBE			DEFINE_BINDING( 9, 9)
#define BINDING_SAMPLER_CUBEMAP_GEM0				DEFINE_BINDING(10,10)
#define BINDING_SAMPLER_CUBEMAP_GEM1				DEFINE_BINDING(11,11)
#define BINDING_SAMPLER_TEMPORARY					DEFINE_BINDING(12,12)
#define BINDING_SAMPLER_DEPTH_SHADOW				DEFINE_BINDING(13,13)
#define BINDING_SAMPLER_DISPLACEMENT0				DEFINE_BINDING(14,14)
#define BINDING_SAMPLER_DIR_LIT_COLOR				DEFINE_BINDING(15,15)
#define BINDING_SAMPLER_DISPLACEMENT1				DEFINE_BINDING(10,16)
#define BINDING_SAMPLER_MIRROR						DEFINE_BINDING(11,17)
#define BINDING_SAMPLER_GBUF_BC						DEFINE_BINDING(13,18)
#define BINDING_SAMPLER_GBUF_NRM					DEFINE_BINDING(14,19)
#define BINDING_SAMPLER_SHADOW_MAP				    DEFINE_BINDING(13,20)
#define BINDING_SAMPLER_PROG_TEXTURE0				DEFINE_BINDING(14,21)
#define BINDING_SAMPLER_MATERIAL_LIGHT_SPHERE		DEFINE_BINDING( 9,22)
#define BINDING_SAMPLER_EXPOSURE					DEFINE_BINDING(14,23)
#define BINDING_SAMPLER_PROC_TEXTURE_2D				DEFINE_BINDING(14,24)
#define BINDING_SAMPLER_PROC_TEXTURE_3D				DEFINE_BINDING(14,25)
#define BINDING_SAMPLER_UNIFORM4					DEFINE_BINDING(14,27)
#define BINDING_SAMPLER_PROG_CUBEMAP_GEM0			DEFINE_BINDING(14,28)
#define BINDING_SAMPLER_CAUSTICS_3D					DEFINE_BINDING(14,30)
